service: nest-serverless

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-dotenv-plugin

provider:
  name: aws
  profile: default
  region: us-east-1
  stage: dev
  runtime: nodejs14.x

package:
  exclude:
    - src/**
    - test/**

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  optimize:
    external: ["swagger-ui-dist"]
